run:
  concurrency: 4
  timeout: 3m
  go: "1.21"
  skip-files:
    - _test\.go
    - _mock\.go
    - main.go

linters:
  disable-all: true
  enable:
    - errcheck
    - gomodguard
    - cyclop
    - gocritic
    - goconst
    - whitespace
    - unused
    - varnamelen
    - funlen
    - goimports
    - lll
    - varnamelen
    - funlen

severity:
  default-severity: error

linters-settings:
  funlen:
    lines: 180
    statements: 60
  cyclop:
    max-complexity: 12
