service: UserAPI

provider:
  name: aws
  runtime: go1.x
  region: us-west-1

package:
  patterns:
    - "!./**/**"
    - "user-api"

functions:
  UserAPI:
    handler: user-api
    environment: ${file(env.${opt:stage, self:provider.stage}.json)}
    events:
      - http:
          method: GET
          path: /health
          cors:
            origin: "*"
      - http:
          method: POST
          path: /user
          cors:
            origin: "*"
      - http:
          method: GET
          path: /user/identifier/{userIdentifier}/password/{userPassword}
          cors:
            origin: "*"
      - http:
          method: GET
          path: /user/{userId}/refreshToken/{refreshToken}
          cors:
            origin: "*"
