service: UserAPI

provider:
  name: aws
  runtime: go1.x
  region: us-west-1
  apiGateway:
    disableDefaultEndpoint: true

package:
  patterns:
    - "!./**/**"
    - "user-api"

functions:
  UserAPI:
    handler: user-api
    environment: ${file(env.${opt:stage, self:provider.stage}.json)}
    events:
      - http:
          method: GET
          path: /health
          cors: true
      - http:
          method: POST
          path: /user
          cors: true
      - http:
          method: PATCH
          path: /user
          cors: true
      - http:
          method: GET
          path: /user/email/{userEmail}/password/{userPassword}
          cors: true
      - http:
          method: GET
          path: /user/{userId}/refreshToken/{refreshToken}
          cors: true
