service: UserAPI
frameworkVersion: "3"

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  region: us-west-1
  environment: ${file(env.${opt:stage, self:provider.stage}.json)}

package:
  individually: true

functions:
  register:
    handler: bootstrap
    package:
      artifact: build/register/register.zip

  login:
    handler: bootstrap
    package:
      artifact: build/login/login.zip

  getUserById:
    handler: bootstrap
    package:
      artifact: build/getUserById/getUserById.zip

  updateUserById:
    handler: bootstrap
    package:
      artifact: build/updateUserById/updateUserById.zip

  getAccessTokenViaRefreshToken:
    handler: bootstrap
    package:
      artifact: build/getAccessTokenViaRefreshToken/getAccessTokenViaRefreshToken.zip
