service: UserAPI

provider:
  name: aws
  runtime: go1.x
  region: us-west-1

functions:
  UserAPI:
    handler: user-api
    environment: ${file(env.${opt:stage, self:provider.stage}.json)}
    events:
      - http:
          method: GET
          path: /health
      - http:
          method: POST
          path: /user
      - http:
          method: GET
          path: /user/email/{userEmail}/password/{userPassword}
      - http:
          method: GET
          path: /user/{userId}/refreshToken/{refreshToken}
