// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository.go
//
// Generated by this command:
//
//	mockgen --source=internal/repository.go --destination=internal/repository_mock.go --package=user
//
// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"
	time "time"
	cerror "user-service/pkg/cerror"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindRefreshTokenByUserId mocks base method.
func (m *MockRepository) FindRefreshTokenByUserId(ctx context.Context, userId, token string, tokenCreatedAt, tokenExpiresAt time.Time) (*RefreshTokenHistoryTable, *cerror.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshTokenByUserId", ctx, userId, token, tokenCreatedAt, tokenExpiresAt)
	ret0, _ := ret[0].(*RefreshTokenHistoryTable)
	ret1, _ := ret[1].(*cerror.CustomError)
	return ret0, ret1
}

// FindRefreshTokenByUserId indicates an expected call of FindRefreshTokenByUserId.
func (mr *MockRepositoryMockRecorder) FindRefreshTokenByUserId(ctx, userId, token, tokenCreatedAt, tokenExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshTokenByUserId", reflect.TypeOf((*MockRepository)(nil).FindRefreshTokenByUserId), ctx, userId, token, tokenCreatedAt, tokenExpiresAt)
}

// FindUserWithEmail mocks base method.
func (m *MockRepository) FindUserWithEmail(ctx context.Context, email string) (*Table, *cerror.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserWithEmail", ctx, email)
	ret0, _ := ret[0].(*Table)
	ret1, _ := ret[1].(*cerror.CustomError)
	return ret0, ret1
}

// FindUserWithEmail indicates an expected call of FindUserWithEmail.
func (mr *MockRepositoryMockRecorder) FindUserWithEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserWithEmail", reflect.TypeOf((*MockRepository)(nil).FindUserWithEmail), ctx, email)
}

// FindUserWithId mocks base method.
func (m *MockRepository) FindUserWithId(ctx context.Context, userId string) (*Table, *cerror.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserWithId", ctx, userId)
	ret0, _ := ret[0].(*Table)
	ret1, _ := ret[1].(*cerror.CustomError)
	return ret0, ret1
}

// FindUserWithId indicates an expected call of FindUserWithId.
func (mr *MockRepositoryMockRecorder) FindUserWithId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserWithId", reflect.TypeOf((*MockRepository)(nil).FindUserWithId), ctx, userId)
}

// InsertIdentityVerificationHistory mocks base method.
func (m *MockRepository) InsertIdentityVerificationHistory(ctx context.Context, identityVerification *IdentityVerificationTable) *cerror.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertIdentityVerificationHistory", ctx, identityVerification)
	ret0, _ := ret[0].(*cerror.CustomError)
	return ret0
}

// InsertIdentityVerificationHistory indicates an expected call of InsertIdentityVerificationHistory.
func (mr *MockRepositoryMockRecorder) InsertIdentityVerificationHistory(ctx, identityVerification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertIdentityVerificationHistory", reflect.TypeOf((*MockRepository)(nil).InsertIdentityVerificationHistory), ctx, identityVerification)
}

// InsertRefreshTokenHistory mocks base method.
func (m *MockRepository) InsertRefreshTokenHistory(ctx context.Context, refreshTokenHistory *RefreshTokenHistoryTable) *cerror.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRefreshTokenHistory", ctx, refreshTokenHistory)
	ret0, _ := ret[0].(*cerror.CustomError)
	return ret0
}

// InsertRefreshTokenHistory indicates an expected call of InsertRefreshTokenHistory.
func (mr *MockRepositoryMockRecorder) InsertRefreshTokenHistory(ctx, refreshTokenHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRefreshTokenHistory", reflect.TypeOf((*MockRepository)(nil).InsertRefreshTokenHistory), ctx, refreshTokenHistory)
}

// InsertUser mocks base method.
func (m *MockRepository) InsertUser(ctx context.Context, user *Table) *cerror.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, user)
	ret0, _ := ret[0].(*cerror.CustomError)
	return ret0
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockRepositoryMockRecorder) InsertUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockRepository)(nil).InsertUser), ctx, user)
}

// SendEmailVerificationMessage mocks base method.
func (m *MockRepository) SendEmailVerificationMessage(ctx context.Context, verificationSqsMessageBody *EmailVerificationSqsMessageBody) *cerror.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailVerificationMessage", ctx, verificationSqsMessageBody)
	ret0, _ := ret[0].(*cerror.CustomError)
	return ret0
}

// SendEmailVerificationMessage indicates an expected call of SendEmailVerificationMessage.
func (mr *MockRepositoryMockRecorder) SendEmailVerificationMessage(ctx, verificationSqsMessageBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailVerificationMessage", reflect.TypeOf((*MockRepository)(nil).SendEmailVerificationMessage), ctx, verificationSqsMessageBody)
}

// UpdateUserById mocks base method.
func (m *MockRepository) UpdateUserById(ctx context.Context, userId string, user *UpdateUserPayload) *cerror.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserById", ctx, userId, user)
	ret0, _ := ret[0].(*cerror.CustomError)
	return ret0
}

// UpdateUserById indicates an expected call of UpdateUserById.
func (mr *MockRepositoryMockRecorder) UpdateUserById(ctx, userId, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserById", reflect.TypeOf((*MockRepository)(nil).UpdateUserById), ctx, userId, user)
}
