// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service.go
//
// Generated by this command:
//
//	mockgen --source=internal/service.go --destination=internal/service_mock.go --package=user
//
// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"
	cerror "user-service/pkg/cerror"
	jwt_generator "user-service/pkg/jwt_generator"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAccessTokenByRefreshToken mocks base method.
func (m *MockService) GetAccessTokenByRefreshToken(ctx context.Context, userId, refreshToken string) (*AccessTokenPayload, *cerror.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenByRefreshToken", ctx, userId, refreshToken)
	ret0, _ := ret[0].(*AccessTokenPayload)
	ret1, _ := ret[1].(*cerror.CustomError)
	return ret0, ret1
}

// GetAccessTokenByRefreshToken indicates an expected call of GetAccessTokenByRefreshToken.
func (mr *MockServiceMockRecorder) GetAccessTokenByRefreshToken(ctx, userId, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenByRefreshToken", reflect.TypeOf((*MockService)(nil).GetAccessTokenByRefreshToken), ctx, userId, refreshToken)
}

// Login mocks base method.
func (m *MockService) Login(ctx context.Context, user *LoginPayload) (*jwt_generator.Tokens, *cerror.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(*jwt_generator.Tokens)
	ret1, _ := ret[1].(*cerror.CustomError)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockServiceMockRecorder) Login(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockService)(nil).Login), ctx, user)
}

// Register mocks base method.
func (m *MockService) Register(ctx context.Context, user *RegisterPayload) (*jwt_generator.Tokens, *cerror.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(*jwt_generator.Tokens)
	ret1, _ := ret[1].(*cerror.CustomError)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockServiceMockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockService)(nil).Register), ctx, user)
}

// UpdateUserById mocks base method.
func (m *MockService) UpdateUserById(ctx context.Context, userId string, user *UpdateUserPayload) (*jwt_generator.Tokens, *cerror.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserById", ctx, userId, user)
	ret0, _ := ret[0].(*jwt_generator.Tokens)
	ret1, _ := ret[1].(*cerror.CustomError)
	return ret0, ret1
}

// UpdateUserById indicates an expected call of UpdateUserById.
func (mr *MockServiceMockRecorder) UpdateUserById(ctx, userId, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserById", reflect.TypeOf((*MockService)(nil).UpdateUserById), ctx, userId, user)
}
