// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service.go

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"
	jwt_generator "user-api/pkg/jwt_generator"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAccessTokenByRefreshToken mocks base method.
func (m *MockService) GetAccessTokenByRefreshToken(ctx context.Context, userId, refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenByRefreshToken", ctx, userId, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessTokenByRefreshToken indicates an expected call of GetAccessTokenByRefreshToken.
func (mr *MockServiceMockRecorder) GetAccessTokenByRefreshToken(ctx, userId, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenByRefreshToken", reflect.TypeOf((*MockService)(nil).GetAccessTokenByRefreshToken), ctx, userId, refreshToken)
}

// Login mocks base method.
func (m *MockService) Login(ctx context.Context, user *UserLoginPayload) (*jwt_generator.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(*jwt_generator.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockServiceMockRecorder) Login(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockService)(nil).Login), ctx, user)
}

// Register mocks base method.
func (m *MockService) Register(ctx context.Context, user *UserRegisterPayload) (*jwt_generator.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(*jwt_generator.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockServiceMockRecorder) Register(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockService)(nil).Register), ctx, user)
}

// VerifyAccessToken mocks base method.
func (m *MockService) VerifyAccessToken(ctx context.Context, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockServiceMockRecorder) VerifyAccessToken(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockService)(nil).VerifyAccessToken), ctx, accessToken)
}
